/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './constants/**/*.{js,jsx,ts,tsx}',
    './navigation/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
    './state/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        solarized: {
          base03: '#002b36',
          base02: '#073642',
          base01: '#586e75',
          base00: '#657b83',
          base0: '#839496',
          base1: '#93a1a1',
          base2: '#eee8d5',
          base3: '#fdf6e3',
          yellow: '#b58900',
          orange: '#cb4b16',
          red: '#dc322f',
          magenta: '#d33682',
          violet: '#6c71c4',
          blue: '#268bd2',
          cyan: '#2aa198',
          green: '#859900',
        },
        gymflow: {
          primary: '#2f855a',
          primaryDark: '#6ee7a8',
          primaryHover: '#276f4b',
          primaryHoverDark: '#52c98d',
          borderDark: '#31565f',
          accentSoft: '#f4e7b5',
          accentSoftDark: '#3a3f2c',
          dangerHover: '#b91c1c',
          errorDark: '#ff8f8f',
          mutedHover: '#e2dcc9',
          mutedHoverDark: '#0b4350',
          selector: '#e2dcc9',
          selectorHover: '#d8d1bd',
          selectorDark: '#002f3b',
          today: '#eadb9f',
        },
      },
    },
  },
  plugins: [],
};
